### ISSUE TITLE
The library name in the README file is wrong.

### ISSUE THREAD

**Issue by danielortizlira** [maximbircu/pull-request-checkstyle#6]
## Abstract

This line in the `README` file is wrong:
`uses: maximbircu/github-action-pull-request-checkstyle@v1.0.0`

As you can see it is pointing to the wrong repository and it will rise an error like `##[error]An action could not be found at the URI 'https://api.github.com/repos/....` when setting the job. 

**Expected**
The line should be `uses: maximbircu/pull-request-checkstyle@v1.0.0`

**Comment by maximbircu** [comment]
Hi!
Thanks for contributing, I'll check why the CI is failing and will review your PR today. 👍
